antvis/antvis.github.io

gatsby-config.js
package.json

https://github.com/antvis/antvis.github.io/issues/18#issuecomment-552097061

feat: redirect old urls

---

site/components/bannerSVG/bannerSVG.tsx

chore: compress image

---

site/locale.json

close https://github.com/antvis/gatsby-theme-antv/issues/52

fix English document title

---

site/components/DecisionTree/DecisionTree.tsx
site/data/decision-tree-chartype.json
site/data/decision-tree-datatype.json
site/data/decision-tree-goal.json

fix: the links for decision tree
add: a g2plot demo to decision tree

fix: links

---

package.json
site/components/DecisionTree/DecisionTree.module.less
site/components/Products/Products.module.less
site/components/ResourceCard/ResourceCard.module.less
site/components/Resources/Resources.tsx

fix: background width for pages. 
fix: logo for resources. 
fix: new version of theme

Background width

---

site/components/DecisionTree/DecisionTree.tsx

Graph hover style

---

package.json
site/pages/index.zh.tsx

chore: update notifications.

---

.github/workflows/preview.yml

https://github.com/afc163/surge-preview

refactor: use afc163/surge-preview

---

.github/workflows/preview.yml

https://github.com/antvis/antvis.github.io/pull/85#issuecomment-723778791

fix: surge preview in wrong ref

---

package.json
site/components/Banner/Banner.tsx
site/components/DemoTwo/DemoTwo.js
site/components/DemoTwo/DemoTwo.module.less

feat: 马赛克拼图功能

---

site/components/Banner/Banner.module.less
site/components/Banner/Banner.tsx
site/data/banner-link.json

feat: 首页about添加站点入口

---

site/pages/d2.less
site/pages/d2.zh.tsx

feat: new texts and touchstart listener

feat: new texts and touchstart listener

---

site/pages/d2.less
site/pages/d2.zh.tsx

feat: response sizes

---

site/pages/d2.less
site/pages/d2.zh.tsx

chore: update styles

---

site/pages/d2.less
site/pages/d2.zh.tsx

fix: update sticker srcs

---

site/pages/d2.zh.tsx

fix: last button img

---

site/pages/d2.less
site/pages/d2.zh.tsx

feat: qrcode for pad and pc

---

site/components/D2Chart/D2Chart.tsx
site/components/D2Chart/shapes/breath-point.ts
site/pages/d2.less
site/pages/d2.zh.tsx

- feat: delete light theme; 
- fix: texts
- fix: 修改 pop 流行音乐 crash
- feat: 修改柱状玫瑰图的颜色

feat: delete light theme; fix: texts

---

site/pages/d2.zh.tsx

chore: update the bottom imgs and remove the lottery code

chore: update the bottom imgs and remove the lottery code

---

site/data/contributors.tsx

Update contributors: buming github link

---

site/data/banner-info.json

- fix: update 404 g6 demo links

fix: update 404 g6 demo links

---

site/components/Banner/Banner.tsx

fix: 使用 logo 尝试替换百度搜索引擎爬虫获取的快照图片

fix: 使用 logo 尝试替换百度搜索引擎爬虫获取的快照图片

---

package.json
site/components/Banner/Banner.module.less
site/components/Banner/Banner.tsx
site/components/Products/Products.tsx
site/components/Products/getProducts.tsx
site/data/banner-info.json
site/data/banner-link.json

feat: 2021 官网产品大图升级

---

site/components/Banner/Banner.tsx
site/components/Banner/helper.ts
site/data/banner-info.json
site/data/banner-link.json

- refactor(banner): 修复 banner 部分的场景 demo 没有跟随切换国内镜像
- refactor(banner): banner 部分的产品链接根据是否国内镜像，进行调整

china mirror link

---

404.html
index.html

docs: fix header to head

---

site/components/FamousPersons/index.tsx
site/components/ProjectCard/index.tsx
site/components/common/OverflowedText/index.tsx

更具 window 变化自动更新 overflowText 组件

fix: overflowText autoUpdate

---

site/components/Banner/Banner.tsx
site/components/ProjectCard/index.module.less
site/components/ProjectCard/index.tsx

fix: cards add L7

---

site/components/Banner/Banner.module.less
site/components/Banner/Banner.tsx

feat(banner): update images
